services:
  # api:
  #   container_name: deezchatz-api
  #   build:
  #     context: .
  #     dockerfile: Containerfile
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #   env_file:
  #     - .env
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  rmqtt:
    container_name: rmqtt
    image: docker.io/rmqtt/rmqtt:latest
    ports:
      - "1883:1883"
    volumes:
      - ./devenv/rmqtt/rmqtt.toml:/app/rmqtt/rmqtt.toml:Z
      - ./devenv/rmqtt/plugins/rmqtt-session-storage.toml:/app/rmqtt/rmqtt-plugins/rmqtt-session-storage.toml:Z
      - ./devenv/rmqtt/plugins/rmqtt-message-storage.toml:/app/rmqtt/rmqtt-plugins/rmqtt-message-storage.toml:Z
      - ./devenv/rmqtt/plugins/rmqtt-web-hook.toml:/app/rmqtt/rmqtt-plugins/rmqtt-web-hook.toml:Z
      - ./devenv/rmqtt/hook.log:/var/log/rmqtt/hook.log:Z
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"


