services:
  api:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://10.0.2.16:6379
    depends_on: [] # No local dependencies needed anymore
