name: Build and Push OCI Image

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# jobs:
#   build-and-push:
#     runs-on: personal-macbook

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Verify Docker
#         run: |
#           which docker
#           docker version
#           docker info

#       - name: Login to Codeberg Registry
#         run: |
#           echo "${{ secrets.CB_TOKEN }}" | docker login codeberg.org \
#             -u "${{ secrets.CB_USERNAME }}" \
#             --password-stdin

#       - name: Build image
#         run: |
#           docker build \
#             -f Containerfile \
#             -t codeberg.org/${{ env.IMAGE_NAME }}:latest \
#             .

#       - name: Push image
#         run: |
#           docker push codeberg.org/${{ env.IMAGE_NAME }}:latest
jobs:
  build-and-push:
    runs-on: personal-macbook

    container:
    image: docker:29-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Login to Codeberg Registry
        run: |
          echo "${{ secrets.CB_TOKEN }}" | docker login codeberg.org \
            -u "${{ secrets.CB_USERNAME }}" \
            --password-stdin

      - name: Extract metadata (tags, labels) for OCI
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest

      - name: Build image
        run: |
          docker build \
            -f Containerfile \
            -t codeberg.org/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push image
        run: |
          docker push codeberg.org/${{ env.IMAGE_NAME }}:latest
